[package]
name = "scry-aosp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
scry-walker = { path = "../scry-walker" }
scry-store = { path = "../scry-store" }
scry-lang = { path = "../scry-lang" }
